# Importing Dataset

In [102]:
import pandas as pd

In [103]:
df = pd.read_excel(r'D:\My Drive\spam.xlsx')
df 

v1                                                 v2 Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...    ...                                                ...        ...   
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will �_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN  
1           NaN        NaN  
2           NaN        NaN  
3           NaN        NaN  
4           NaN        NaN  
...         ...        ...  
5567        NaN        NaN  
5568        NaN        NaN  
5569        NaN        NaN  
5570        NaN        NaN  
5571        NaN        NaN  

[5572 rows x 5 columns]

# Cleaning Dataset

In [104]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   v1          5572 non-null   object
 1   v2          5572 non-null   object
 2   Unnamed: 2  50 non-null     object
 3   Unnamed: 3  12 non-null     object
 4   Unnamed: 4  6 non-null      object
dtypes: object(5)
memory usage: 217.8+ KB


In [105]:
df.isnull().sum()

v1               0
v2               0
Unnamed: 2    5522
Unnamed: 3    5560
Unnamed: 4    5566
dtype: int64

In [106]:
df.drop(columns=['Unnamed: 2','Unnamed: 3','Unnamed: 4'],inplace=True)
df 

v1                                                 v2
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will �_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [107]:
df.duplicated().sum()

403

In [108]:
df = df.drop_duplicates()
df 

v1                                                 v2
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will �_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5169 rows x 2 columns]

In [109]:
df.duplicated().sum()

0

In [110]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5169 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   v1      5169 non-null   object
 1   v2      5169 non-null   object
dtypes: object(2)
memory usage: 121.1+ KB


In [111]:
df['v1'].value_counts()

ham     4516
spam     653
Name: v1, dtype: int64

# Convert into Lower Case

In [112]:
df['v2']=df['v2'].str.lower()  

C:\Users\Admin\AppData\Local\Temp\ipykernel_11804\545533427.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['v2']=df['v2'].str.lower()


In [113]:
df.head(2)

v1                                                 v2
0  ham  go until jurong point, crazy.. available only ...
1  ham                      ok lar... joking wif u oni...

# Remove Unwanted Data like html tags

In [114]:
import re
def remove_html_tags(text):
    pattern = re.compile('<.*?>')
    return pattern.sub(r'',str(text))

In [115]:
df['v2']=df['v2'].apply(remove_html_tags)

C:\Users\Admin\AppData\Local\Temp\ipykernel_11804\3744607702.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['v2']=df['v2'].apply(remove_html_tags)


In [116]:
df.head(2)

v1                                                 v2
0  ham  go until jurong point, crazy.. available only ...
1  ham                      ok lar... joking wif u oni...

# Remove url

In [117]:
def remove_url(text):
    pattern = re.compile(r'http?://\S+|www\.\S+')
    return pattern.sub(r'',str(text))

In [118]:
df['v2']=df['v2'].apply(remove_url)

C:\Users\Admin\AppData\Local\Temp\ipykernel_11804\198366013.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['v2']=df['v2'].apply(remove_url)


In [119]:
df.head(2)

v1                                                 v2
0  ham  go until jurong point, crazy.. available only ...
1  ham                      ok lar... joking wif u oni...

# Remove Punctuation (!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~)

In [120]:
import string
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [121]:
exclude = string.punctuation

In [122]:
def remove_punc(text):
    return text.translate(str.maketrans('','',exclude))

In [123]:
df['v2']=df['v2'].apply(remove_punc)

C:\Users\Admin\AppData\Local\Temp\ipykernel_11804\1202471990.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['v2']=df['v2'].apply(remove_punc)


In [124]:
df.head(2)

v1                                                 v2
0  ham  go until jurong point crazy available only in ...
1  ham                            ok lar joking wif u oni

# Correct Spelling for that pip install textblob (maner - manner)

In [125]:
from textblob import TextBlob

In [126]:
def correct_spelling(text):
    return TextBlob(text).correct().string      

In [127]:
df['v2']=df['v2'].apply(correct_spelling)

C:\Users\Admin\AppData\Local\Temp\ipykernel_11804\2979715371.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['v2']=df['v2'].apply(correct_spelling)


In [128]:
df.head(2)

v1                                                 v2
0  ham  go until during point crazy available only in ...
1  ham                              ok war joking if u on

# Remove Stop Words (a, the, etc...) for that pip install nltk

In [129]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [130]:
from nltk.corpus import stopwords
stop_words = set(stopwords.words('english')) # Choose the language for stopwords 
stop_words 

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 'r

In [131]:
def remove_stopwords(text):
   new_text = []
   for word in text.split():
      if word not in stopwords.words('english'):
         new_text.append(word)
   return" ".join(new_text) 

In [132]:
df['v2']=df['v2'].apply(remove_stopwords)

C:\Users\Admin\AppData\Local\Temp\ipykernel_11804\2919632685.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['v2']=df['v2'].apply(remove_stopwords)


In [133]:
df.head(2)

v1                                                 v2
0  ham  go point crazy available boris n great world l...
1  ham                                    ok war joking u

# Remove Emojies

In [134]:
import re
def remove_emoji(text):
    emoji_pattern = re.compile("["
                        u"\U0001F600-\U0001F64F"  # emoticons
                        u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                        u"\U0001F680-\U0001F6FF"  # transport & map symbols
                        u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                        u"\U00002500-\U00002BEF"  # chinese characters
                        u"\U00002702-\U000027B0"
                        u"\U00002702-\U000027B0"
                        u"\U000024C2-\U0001F251"
                        u"\U0001f926-\U0001f937"
                        u"\U00010000-\U0010ffff"
                        u"\u2640-\u2642"
                        u"\u2600-\u2B55"
                        u"\u200d"
                        u"\u23cf"
                        u"\u23e9"
                        u"\u231a"
                        u"\ufe0f"  # dingbats
                        u"\u3030"  
                       "]+",flags=re.UNICODE)
    return emoji_pattern.sub(r'',text)   

In [135]:
df['v2']=df['v2'].apply(remove_emoji)

C:\Users\Admin\AppData\Local\Temp\ipykernel_11804\644280684.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['v2']=df['v2'].apply(remove_emoji)


In [136]:
df

v1                                                 v2
0      ham  go point crazy available boris n great world l...
1      ham                                    ok war joking u
2     spam  free entry 2 wily come win cup final must may ...
3      ham                    u dun say early u c already say
4      ham          ah dont think goes us lives around though
...    ...                                                ...
5567  spam  time tried 2 contact u u 750 pound prize 2 cla...
5568   ham                          b going esplanade fr home
5569   ham                              pity mood suggestions
5570   ham  guy itching acted like id interested buying so...
5571   ham                                     roll true name

[5169 rows x 2 columns]

# Convert Emoji to Text for that pip install emoji

In [137]:
import emoji

In [138]:
print(emoji.demojize('python is 😍'))

python is :smiling_face_with_heart-eyes:


# Stemming Words (likes, liked, likely, liking - like)

In [139]:
from nltk.stem.porter import PorterStemmer

In [140]:
ps = PorterStemmer()
def stem_words(text):
    return " ".join([ps.stem(word) for word in text.split()])

In [141]:
df['v2']=df['v2'].apply(stem_words)

C:\Users\Admin\AppData\Local\Temp\ipykernel_11804\2030314067.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['v2']=df['v2'].apply(stem_words)


In [142]:
df

v1                                                 v2
0      ham  go point crazi avail bori n great world la e b...
1      ham                                      ok war joke u
2     spam  free entri 2 wili come win cup final must may ...
3      ham                    u dun say earli u c alreadi say
4      ham            ah dont think goe us live around though
...    ...                                                ...
5567  spam  time tri 2 contact u u 750 pound prize 2 claim...
5568   ham                              b go esplanad fr home
5569   ham                                  piti mood suggest
5570   ham  guy itch act like id interest buy someth els n...
5571   ham                                     roll true name

[5169 rows x 2 columns]

# Apply Bag of Words(BOW) Model

In [143]:
from sklearn.feature_extraction.text import CountVectorizer

In [144]:
cv = CountVectorizer() 

In [145]:
bow = cv.fit_transform(df['v2'])

In [146]:
bow

<5169x5767 sparse matrix of type '<class 'numpy.int64'>'
	with 39257 stored elements in Compressed Sparse Row format>

In [147]:
print(cv.vocabulary_)

{'go': 2488, 'point': 4031, 'crazi': 1683, 'avail': 992, 'bori': 1198, 'great': 2553, 'world': 5673, 'la': 3066, 'buffet': 1279, 'line': 3174, 'got': 2526, 'wat': 5529, 'ok': 3769, 'war': 5520, 'joke': 2974, 'free': 2356, 'entri': 2074, 'wili': 5624, 'come': 1564, 'win': 5628, 'cup': 1710, 'final': 2249, 'must': 3560, 'may': 3367, '2005': 408, 'text': 5125, '87121': 667, 'receiv': 4273, 'question': 4206, 'txt': 5333, 'rate': 4243, 'appli': 913, '08452810075over18': 71, 'dun': 1981, 'say': 4481, 'earli': 1991, 'alreadi': 837, 'ah': 802, 'dont': 1920, 'think': 5170, 'goe': 2495, 'us': 5407, 'live': 3192, 'around': 941, 'though': 5175, 'freemen': 2362, 'hey': 2690, 'darl': 1744, 'week': 5557, 'word': 5665, 'back': 1023, 'id': 2806, 'like': 3167, 'fun': 2402, 'still': 4900, 'xxx': 5706, 'st': 4857, 'cog': 1546, 'send': 4533, '150': 344, 'rev': 4363, 'even': 2108, 'brother': 1264, 'speak': 4809, 'treat': 5292, 'aid': 805, 'patent': 3904, 'per': 3930, 'request': 4335, 'sell': 4529, 'minnamin

In [148]:
print(bow[0].toarray())

[[0 0 0 ... 0 0 0]]


In [150]:
matrix = cv.fit_transform(df['v2']).toarray()
matrix

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

# Apply BOW Model with n-gram

In [151]:
cv = CountVectorizer(ngram_range=(2,2)) 

In [152]:
bow = cv.fit_transform(df['v2'])

In [153]:
bow

<5169x27896 sparse matrix of type '<class 'numpy.int64'>'
	with 35877 stored elements in Compressed Sparse Row format>

In [154]:
print(cv.vocabulary_)

{'go point': 10002, 'point crazi': 18743, 'crazi avail': 5583, 'avail bori': 2197, 'bori great': 3173, 'great world': 10584, 'world la': 27412, 'la buffet': 12971, 'buffet line': 3473, 'line got': 13910, 'got wat': 10473, 'ok war': 17408, 'war joke': 26328, 'free entri': 8819, 'entri wili': 7551, 'wili come': 27024, 'come win': 5154, 'win cup': 27042, 'cup final': 5664, 'final must': 8319, 'must may': 16305, 'may 2005': 14970, '2005 text': 503, 'text 87121': 23919, '87121 receiv': 841, 'receiv entri': 19751, 'entri question': 7547, 'question txt': 19374, 'txt rate': 25431, 'rate appli': 19505, 'appli 08452810075over18': 1836, 'dun say': 7136, 'say earli': 20702, 'earli alreadi': 7152, 'alreadi say': 1371, 'ah dont': 1209, 'dont think': 6868, 'think goe': 24302, 'goe us': 10147, 'us live': 25693, 'live around': 14012, 'around though': 1962, 'freemen hey': 8920, 'hey darl': 11281, 'darl week': 5895, 'week word': 26682, 'word back': 27277, 'back id': 2436, 'id like': 11971, 'like fun': 13

In [155]:
print(bow[0].toarray())

[[0 0 0 ... 0 0 0]]


In [156]:
matrix = cv.fit_transform(df['v2']).toarray()
matrix

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

# Apply TF-IDF (Term frequency-inverse Document Frequency) Model

In [157]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [158]:
tfidf = TfidfVectorizer() 

In [159]:
bow = tfidf.fit_transform(df['v2'])

In [160]:
bow

<5169x5767 sparse matrix of type '<class 'numpy.float64'>'
	with 39257 stored elements in Compressed Sparse Row format>

In [161]:
print(tfidf.idf_)
print(tfidf.get_feature_names_out())

[8.45201568 8.85748079 8.85748079 ... 8.85748079 8.85748079 8.85748079]
['008704050406' '0089mi' '0121' ... 'zindgi' 'zogtoriu' 'zyada']


In [162]:
print(bow[0].toarray())

[[0. 0. 0. ... 0. 0. 0.]]


In [163]:
matrix = tfidf.fit_transform(df['v2']).toarray()
matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

# Preprocessing

In [164]:
df['v1'] = df['v1'].map({'spam':1,'ham':0})
df 

C:\Users\Admin\AppData\Local\Temp\ipykernel_11804\1460614221.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['v1'] = df['v1'].map({'spam':1,'ham':0})


v1                                                 v2
0      0  go point crazi avail bori n great world la e b...
1      0                                      ok war joke u
2      1  free entri 2 wili come win cup final must may ...
3      0                    u dun say earli u c alreadi say
4      0            ah dont think goe us live around though
...   ..                                                ...
5567   1  time tri 2 contact u u 750 pound prize 2 claim...
5568   0                              b go esplanad fr home
5569   0                                  piti mood suggest
5570   0  guy itch act like id interest buy someth els n...
5571   0                                     roll true name

[5169 rows x 2 columns]

# Defining X & y for Training and Testing Dataset

In [165]:
X = matrix
y = df[['v1']]

# Split Dataset into Training & Testing

In [166]:
from sklearn.model_selection import train_test_split 

In [167]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=0) 

# Linear Regression

In [168]:
from sklearn.linear_model import LinearRegression 

In [169]:
lr = LinearRegression() 

In [170]:
model = lr.fit(X_train,y_train) 

In [171]:
y_pred = lr.predict(X_test)

In [172]:
from sklearn.metrics import r2_score

In [173]:
print('R2_Score: ',r2_score(y_test,y_pred))

R2_Score:  -4.815873405555087e+25


# RIDGE

In [174]:
from sklearn.linear_model import Ridge

In [175]:
r=Ridge(alpha=0.0001) 

In [176]:
r.fit(X_train,y_train)

Ridge(alpha=0.0001)

In [177]:
y_pred = r.predict(X_test) 

In [178]:
print('R2_Score: ',r2_score(y_test,y_pred))

R2_Score:  0.5841259564779251


# LASSO

In [179]:
from sklearn.linear_model import Lasso 

In [180]:
l = Lasso(alpha=0.01)

In [181]:
l.fit(X_train,y_train) 

Lasso(alpha=0.01)

In [182]:
y_pred = l.predict(X_test) 

In [183]:
print('R2_Score: ',r2_score(y_test,y_pred))

R2_Score:  -0.004001055895435757


# Decision Tree

In [184]:
from sklearn.tree import DecisionTreeClassifier 

In [185]:
classifier = DecisionTreeClassifier(criterion='entropy',random_state=0)

In [186]:
classifier.fit(X_train,y_train) 

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [187]:
y_pred = classifier.predict(X_test)

In [188]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [189]:
confusion_matrix(y_pred,y_test) 

array([[864,  24],
       [ 21, 125]], dtype=int64)

In [190]:
accuracy_score(y_pred,y_test) 

0.9564796905222437

In [191]:
print(classification_report(y_pred,y_test)) 

              precision    recall  f1-score   support

           0       0.98      0.97      0.97       888
           1       0.84      0.86      0.85       146

    accuracy                           0.96      1034
   macro avg       0.91      0.91      0.91      1034
weighted avg       0.96      0.96      0.96      1034



# Logistic Regression

In [192]:
from sklearn.linear_model import LogisticRegression 

In [193]:
lgr = LogisticRegression()

In [194]:
lgr.fit(X_train,y_train)

c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\utils\validation.py:1183: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [195]:
y_pred = lgr.predict(X_test)

In [196]:
confusion_matrix(y_pred,y_test) 

array([[884,  62],
       [  1,  87]], dtype=int64)

In [197]:
accuracy_score(y_pred,y_test) 

0.9390715667311412

In [198]:
print(classification_report(y_pred,y_test)) 

              precision    recall  f1-score   support

           0       1.00      0.93      0.97       946
           1       0.58      0.99      0.73        88

    accuracy                           0.94      1034
   macro avg       0.79      0.96      0.85      1034
weighted avg       0.96      0.94      0.95      1034



# KNN

In [199]:
from sklearn.neighbors import KNeighborsClassifier

In [200]:
nc = KNeighborsClassifier(n_neighbors=3)

In [201]:
nc.fit(X_train,y_train) 

c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\neighbors\_classification.py:233: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=3)

In [202]:
y_pred = nc.predict(X_test)

In [203]:
confusion_matrix(y_pred,y_test) 

array([[885, 104],
       [  0,  45]], dtype=int64)

In [204]:
accuracy_score(y_pred,y_test) 

0.8994197292069632

In [205]:
print(classification_report(y_pred,y_test)) 

              precision    recall  f1-score   support

           0       1.00      0.89      0.94       989
           1       0.30      1.00      0.46        45

    accuracy                           0.90      1034
   macro avg       0.65      0.95      0.70      1034
weighted avg       0.97      0.90      0.92      1034



# SVC

In [206]:
from sklearn.svm import SVC

In [207]:
classifier_svc = SVC(kernel='linear') 

In [208]:
classifier_svc.fit(X_train,y_train) 

c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\utils\validation.py:1183: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(kernel='linear')

In [209]:
y_pred = classifier_svc.predict(X_test)

In [210]:
confusion_matrix(y_pred,y_test) 

array([[883,  27],
       [  2, 122]], dtype=int64)

In [211]:
accuracy_score(y_pred,y_test) 

0.971953578336557

In [212]:
print(classification_report(y_pred,y_test)) 

              precision    recall  f1-score   support

           0       1.00      0.97      0.98       910
           1       0.82      0.98      0.89       124

    accuracy                           0.97      1034
   macro avg       0.91      0.98      0.94      1034
weighted avg       0.98      0.97      0.97      1034



# Naive Bayes

In [213]:
from sklearn.naive_bayes import GaussianNB

In [214]:
nb = GaussianNB()

In [215]:
nb.fit(X_train,y_train) 

c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\utils\validation.py:1183: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB()

In [216]:
y_pred = nb.predict(X_test)

In [217]:
confusion_matrix(y_pred,y_test) 

array([[730,  28],
       [155, 121]], dtype=int64)

In [218]:
accuracy_score(y_pred,y_test) 

0.8230174081237911

In [219]:
print(classification_report(y_pred,y_test)) 

              precision    recall  f1-score   support

           0       0.82      0.96      0.89       758
           1       0.81      0.44      0.57       276

    accuracy                           0.82      1034
   macro avg       0.82      0.70      0.73      1034
weighted avg       0.82      0.82      0.80      1034

